---
title: "Population Structure"
---


::: {.callout-note}
Differentiate which commands are bash commands, which commands call dependencies within your Pixi environment, and which ones call on containers
:::


## PCA
Replace underscores with nothing
```{.bash}
sed "s/_//g" $VCF > $VCF_renamed.vcf
```

Run PCA generation through plink
```{.bash}
plink --vcf $VCF_renamed.vcf --allow-extra-chr --pca
```


::: {.callout-tip}

plink v1.9 is a lot better and more reliable than plink v2. Always check which version of your software is best suited to your needs!

:::


```{.r}
#PCA
pca_eigenval = read.table("teaching/forest_popgen/plink.eigenval", header = F, sep = " ")
pca_eigenvec = read.delim("teaching/forest_popgen/plink.eigenvec", header = F, sep = " ")

names(pca_eigenvec)[names(pca_eigenvec) == 'V1'] <- 'ID'
pca_eigenvec = pca_eigenvec %>%
  mutate(Population = case_when(
    startsWith(ID, "BIL") ~ "bil",
    startsWith(ID, "BNP") ~ "bnp",
    startsWith(ID, "Her") ~ "her",
    startsWith(ID, "Iss") ~ "iss",
    startsWith(ID, "Kai") ~ "kai",
    startsWith(ID, "Koi") ~ "koi",
    startsWith(ID, "Kot") ~ "kot",
    startsWith(ID, "Luu") ~ "luu",
    startsWith(ID, "Met") ~ "met",
    startsWith(ID, "Mor") ~ "mor",
    startsWith(ID, "Mus") ~ "mus",
    startsWith(ID, "Myl") ~ "myl",
    startsWith(ID, "Pam") ~ "pam",
    startsWith(ID, "Pat") ~ "pat",
    startsWith(ID, "Pet") ~ "pet",
    startsWith(ID, "Puk") ~ "puk",
    startsWith(ID, "Rus") ~ "rus",
    startsWith(ID, "Sig") ~ "sig",
    startsWith(ID, "Skj") ~ "skj",
    startsWith(ID, "eSK") ~ "skj",
    startsWith(ID, "Spk") ~ "spk",
    startsWith(ID, "Sus") ~ "sus",
    startsWith(ID, "Ulv") ~ "ulv",
    startsWith(ID, "Van") ~ "van",
    startsWith(ID, "Ves") ~ "ves"))

pca_eigenvec = pca_eigenvec %>%
  mutate(Location = case_when(
    startsWith(ID, "BIL") ~ "Sweden",
    startsWith(ID, "BNP") ~ "Poland",
    startsWith(ID, "Her") ~ "SWF",
    startsWith(ID, "Iss") ~ "NEF",
    startsWith(ID, "Kai") ~ "NEF",
    startsWith(ID, "Koi") ~ "NEF",
    startsWith(ID, "Kot") ~ "SWF",
    startsWith(ID, "Luu") ~ "SWF",
    startsWith(ID, "Met") ~ "SWF",
    startsWith(ID, "Mor") ~ "Norway",
    startsWith(ID, "Mus") ~ "SWF",
    startsWith(ID, "Myl") ~ "SWF",
    startsWith(ID, "Pam") ~ "NEF",
    startsWith(ID, "Pat") ~ "NEF",
    startsWith(ID, "Pet") ~ "SWF",
    startsWith(ID, "Puk") ~ "SWF",
    startsWith(ID, "Rus") ~ "Russia",
    startsWith(ID, "Sig") ~ "Norway",
    startsWith(ID, "Skj") ~ "Norway",
    startsWith(ID, "eSK") ~ "Norway",
    startsWith(ID, "Spk") ~ "Norway",
    startsWith(ID, "Sus") ~ "SWF",
    startsWith(ID, "Ulv") ~ "NEF",
    startsWith(ID, "Van") ~ "NEF",
    startsWith(ID, "Ves") ~ "SWF"
  ))

row_id <- seq(1, nrow(pca_eigenval))
pca_eigenval$row_id = row_id

#Plot eigenval 
ggplot(pca_eigenval, aes(x = row_id, y = V1)) +
  geom_bar(stat = "identity")

#Plot eigenved
ggplot(pca_eigenvec, aes(x= V4, y= V3, col = Population)) +
  geom_point()
```

## LD (We are not going to do this in the course today)
Use scaffolds where _ are removed. This step is usually very memory intensive, so splitting the dataset into scaffolds is usually necessary. Under normal assumptions you would not expect unique chromosomes to be linked

```{.bash}
plink --vcf $VCF_renamed.vcf --allow-extra-chr --out plink-test --r2 --ld-window-r2 0 --ld-window 0 --ld-window-kb 8000 
```

```{.r}
#from https://www.biostars.org/p/300381/
library(dplyr)
library(stringr)
library(ggplot2)

dfr <-read.delim("in_file",sep="",hea
der=F,check.names=F,stringsAsFactors=F)
colnames(dfr) <- c("dist","rsq")
dfr$distc <- cut(dfr$dist,breaks=seq(from=min(dfr$dist)-1,to=max(dfr$dist)+1,by=10000))
dfr1 <- dfr %>% group_by(distc) %>% summarise(mean=mean(rsq),median=median(rsq))
dfr1 <- dfr1 %>% mutate(start=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"^[0-9-
e+.]+")),

end=as.integer(str_extract(str_replace_all(distc,"[\\(\\)\\[\\]]",""),"[0-9-e+.]+$")),
mid=start+((end-start)/2))

#Plot
ggplot(dfr1, aes(x=start,y=mean))+
    geom_line()

```

## Population Structure

There are many ways to determine population structure. We will use sNMF.


Convert the VCF to a .geno file with LEA in R. Here is some (example code)[https://rdrr.io/bioc/LEA/man/vcf2geno.html]

```{.r}
library(LEA)
library(tidyverse)
# Creation of a file called "example.vcf"
# with 4 SNPs for 3 individuals.
data("example_vcf")
write.table(example_vcf,"example.vcf",col.names =
    c("#CHROM", "POS", "ID", "REF", "ALT", "QUAL", "FILTER", "INFO",
    "FORMAT", "SAMPLE0", "SAMPLE1", "SAMPLE2"),
    row.names = FALSE, quote = FALSE)

# Conversion    from the vcf format ("example.vcf") 
#               to the geno format ("example.geno").
# By default,   the name of the output file is the same name
#               as the input file with a .geno extension.
# Create files: "example.geno",
#               "example.vcfsnp" - SNP informations,
#               "example.removed" - removed lines. 
output = vcf2geno("example.vcf")

# Conversion    from the vcf format ("example.vcf")
#               to the geno format with the output file called "plop.geno".
# Create files: "plop.geno",
#               "plop.vcfsnp" - SNP informations,
#               "plop.removed" - removed lines. 
output = vcf2geno("example.vcf", "plop.geno")

# As force = false and the file "example.geno" already exists,
# nothing happens.
output = vcf2geno("example.vcf", force = FALSE)
```
The converted file can be used by sNMF to create the admixture plots
```{.r}
library(LEA)
library(tidyverse)
### Example of analysis using snmf ###
# Creation of the genotype file: genotypes.geno.
# The data contain 400 SNPs for 50 individuals.
#data("tutorial")
#write.geno(tutorial.R, "genotypes.geno")
################
# running snmf #
################
project.snmf = snmf("yourfiles.GT.FORMAT.geno",
K = 1:20,
entropy = TRUE,
ploidy = 1,
repetitions = 10,
project = "new")
# plot cross-entropy criterion of all runs of the project
plot(project.snmf, cex = 1.2, col = "lightblue", pch = 19)
# get the cross-entropy of the 10 runs for K = 4
ce = cross.entropy(project.snmf, K = 4)
# select the run with the lowest cross-entropy for K = 4
best = which.min(ce)
#add names
metadata = read.table("your .d file", header =T)
indv_snmf = read_tsv("your isolate name filet", col_names = F)
names(indv_snmf) = "Sample"
datalist = list()
for (i in c(6, 7, 8, 9)){
best = which.min(cross.entropy(project.snmf, K = i))
temp = as.data.frame(Q(project.snmf, i, best))
temp= cbind(indv_snmf, temp)
temp = temp %>%
gather("Cluster", "Admix_coef", -"Sample") %>%
mutate(K=i)
datalist[[i]] = as.tibble(temp)
}
snmf_results_per_K = bind_rows(datalist)%>%
inner_join(., metadata, by = c("Sample" = "Isolate")) %>%
unite(ID, Country, Location, Host, col = "for_display", remove = F)
ggplot(snmf_results_per_K, aes(x = reorder(Sample, ID), y = Admix_coef, fill = Cluster,
text = for_display)) +
geom_bar(position = "stack", stat = "identity", show.legend = F) +
facet_grid(K~.) +
theme_bw() +
theme(axis.title = element_blank(),
axis.text.x = element_text(angle = 60, hjust = 1),
legend.title = element_blank())
# display the Q-matrix
#my.colors <- c("tomato", "lightblue",
"olivedrab", "gold")
#barchart(project.snmf, K = 4, run = best,
border = NA, space = 0, col = my.colors,
xlab = "Individuals", ylab = "Ancestry proportions",
main = "Ancestry matrix") -> bp
#axis(1, at = 1:length(bp$order),
labels = bp$order, las = 3, cex.axis = .4)
```